# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import model_manager_grpc_pb2 as model__manager__grpc__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_manager_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelManagerGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListExperiments = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/ListExperiments',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.ListExperimentsResponse.FromString,
                _registered_method=True)
        self.BranchExperiment = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/BranchExperiment',
                request_serializer=model__manager__grpc__pb2.BranchExperimentRequest.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.BasicExperimentResponse.FromString,
                _registered_method=True)
        self.SelectExperiment = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/SelectExperiment',
                request_serializer=model__manager__grpc__pb2.SelectExperimentRequest.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.BasicSuccessResponse.FromString,
                _registered_method=True)
        self.SaveExperiment = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/SaveExperiment',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.BasicSuccessResponse.FromString,
                _registered_method=True)
        self.Seed = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/Seed',
                request_serializer=model__manager__grpc__pb2.SeedRequest.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.BasicSuccessResponse.FromString,
                _registered_method=True)
        self.Fit = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/Fit',
                request_serializer=model__manager__grpc__pb2.FitRequest.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.BasicSuccessResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/Predict',
                request_serializer=model__manager__grpc__pb2.PredictRequest.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/model_manager_grpc.ModelManagerGRPC/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=model__manager__grpc__pb2.BasicSuccessResponse.FromString,
                _registered_method=True)


class ModelManagerGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListExperiments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BranchExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelManagerGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListExperiments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExperiments,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=model__manager__grpc__pb2.ListExperimentsResponse.SerializeToString,
            ),
            'BranchExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.BranchExperiment,
                    request_deserializer=model__manager__grpc__pb2.BranchExperimentRequest.FromString,
                    response_serializer=model__manager__grpc__pb2.BasicExperimentResponse.SerializeToString,
            ),
            'SelectExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectExperiment,
                    request_deserializer=model__manager__grpc__pb2.SelectExperimentRequest.FromString,
                    response_serializer=model__manager__grpc__pb2.BasicSuccessResponse.SerializeToString,
            ),
            'SaveExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveExperiment,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=model__manager__grpc__pb2.BasicSuccessResponse.SerializeToString,
            ),
            'Seed': grpc.unary_unary_rpc_method_handler(
                    servicer.Seed,
                    request_deserializer=model__manager__grpc__pb2.SeedRequest.FromString,
                    response_serializer=model__manager__grpc__pb2.BasicSuccessResponse.SerializeToString,
            ),
            'Fit': grpc.unary_unary_rpc_method_handler(
                    servicer.Fit,
                    request_deserializer=model__manager__grpc__pb2.FitRequest.FromString,
                    response_serializer=model__manager__grpc__pb2.BasicSuccessResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=model__manager__grpc__pb2.PredictRequest.FromString,
                    response_serializer=model__manager__grpc__pb2.PredictResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=model__manager__grpc__pb2.BasicSuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_manager_grpc.ModelManagerGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_manager_grpc.ModelManagerGRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelManagerGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListExperiments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/ListExperiments',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            model__manager__grpc__pb2.ListExperimentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BranchExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/BranchExperiment',
            model__manager__grpc__pb2.BranchExperimentRequest.SerializeToString,
            model__manager__grpc__pb2.BasicExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/SelectExperiment',
            model__manager__grpc__pb2.SelectExperimentRequest.SerializeToString,
            model__manager__grpc__pb2.BasicSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/SaveExperiment',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            model__manager__grpc__pb2.BasicSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/Seed',
            model__manager__grpc__pb2.SeedRequest.SerializeToString,
            model__manager__grpc__pb2.BasicSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/Fit',
            model__manager__grpc__pb2.FitRequest.SerializeToString,
            model__manager__grpc__pb2.BasicSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/Predict',
            model__manager__grpc__pb2.PredictRequest.SerializeToString,
            model__manager__grpc__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_manager_grpc.ModelManagerGRPC/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            model__manager__grpc__pb2.BasicSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
